/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Liveness probe. Touches no database and no external service. */
    get: operations['health_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/locations/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description ``GET /api/locations/search?q=&limit=`` (architecture.md AD-6) -- typeahead, US only. */
    get: operations['locations_search_retrieve']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/trips/plan': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** @description Plans a trip against the current HOS rules. A cycle_exhausted trip is still HTTP 200 (architecture.md AD-14) -- see summary.status, warnings and unplanned. */
    post: operations['trips_plan_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Exactly one of ``{lat, lng}`` or ``query`` (architecture.md section 6.1). */
    LocationInput: {
      label?: string
      /** Format: double */
      lat?: number
      /** Format: double */
      lng?: number
      query?: string
    }
    /**
     * @description ``POST /api/trips/plan`` -- architecture.md section 6.1. No ``departure_at`` field: there
     *     is no user-configurable departure time anywhere in this API (Q4, hos-rules.md A-16).
     */
    PlanRequest: {
      current_location: components['schemas']['LocationInput']
      pickup_location: components['schemas']['LocationInput']
      dropoff_location: components['schemas']['LocationInput']
      /** Format: double */
      cycle_used_hours: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_retrieve: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description {status: 'ok', version: string} */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  locations_search_retrieve: {
    parameters: {
      query: {
        limit?: number
        q: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description {results: LocationSuggestion[]} */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
  trips_plan_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PlanRequest']
      }
    }
    responses: {
      /** @description TripPlan -- see docs/api-contract.md */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: unknown
          }
        }
      }
    }
  }
}
